name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.15', '1.20', '1.24', '1.25', '1.26']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: make test
      env:
        TRANSLOADIT_KEY: ${{ secrets.TRANSLOADIT_KEY }}
        TRANSLOADIT_SECRET: ${{ secrets.TRANSLOADIT_SECRET }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v6
      with:
        fail_ci_if_error: true
        files: ./coverage.out
        token: ${{ secrets.CODECOV_TOKEN }}
