name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.11', '1.12', '1.13', '1.14', '1.15', '1.16', '1.17', '1.18', '1.19']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: make test
      env:
        TRANSLOADIT_KEY: ${{ secrets.TRANSLOADIT_KEY }}
        TRANSLOADIT_SECRET: ${{ secrets.TRANSLOADIT_SECRET }}
